#!/bin/bash
# ============================================================
#  OpenClaw One-Click Installer for Oracle Cloud Free Tier
#  Author  : Deepak
#  Version : 1.0.0
#  Usage   : curl -fsSL <raw-url>/install.sh | sudo bash
# ============================================================

set -euo pipefail

# ─── Colors ────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()     { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*"; exit 1; }
section() { echo -e "\n${CYAN}${BOLD}══ $* ══${NC}"; }

# ─── Banner ────────────────────────────────────────────────
echo -e "${CYAN}${BOLD}"
cat << 'EOF'
   ___                  _____ _               
  / _ \ _ __  ___ _ __ / ____| | __ ___      __
 | | | | '_ \/ _ \ '_ \ |    | |/ _` \ \ /\ / /
 | |_| | |_) \  __/ | | |___| | (_| |\ V  V / 
  \___/| .__/ \___|_| |_\___|_|\__,_| \_/\_/  
       |_|    One-Click Installer v1.0.0
       Oracle Cloud Free Tier (ARM / Ampere)
EOF
echo -e "${NC}"

# ─── Root check ────────────────────────────────────────────
[[ $EUID -ne 0 ]] && error "Run as root: sudo bash install.sh"

# ─── Config (override via env vars before running) ─────────
OPENCLAW_PORT="${OPENCLAW_PORT:-3000}"
OPENCLAW_DIR="${OPENCLAW_DIR:-/opt/openclaw}"
TAILSCALE_AUTHKEY="${TAILSCALE_AUTHKEY:-}"   # Optional: set to skip interactive auth
NODE_VERSION="20"

section "STEP 1 — System Update"
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq curl git ufw unzip jq
log "System packages updated"

section "STEP 2 — Node.js ${NODE_VERSION}"
if ! command -v node &>/dev/null || [[ $(node -v | cut -d. -f1 | tr -d 'v') -lt $NODE_VERSION ]]; then
  curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - >/dev/null 2>&1
  apt-get install -y -qq nodejs
  log "Node.js $(node -v) installed"
else
  log "Node.js $(node -v) already present"
fi

section "STEP 3 — Tailscale (Secure Mesh VPN)"
if ! command -v tailscale &>/dev/null; then
  curl -fsSL https://tailscale.com/install.sh | sh >/dev/null 2>&1
  log "Tailscale installed"
else
  log "Tailscale already installed"
fi

# Enable IP forwarding for Tailscale exit node (optional)
echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.d/99-tailscale.conf
echo 'net.ipv6.conf.all.forwarding = 1' >> /etc/sysctl.d/99-tailscale.conf
sysctl -p /etc/sysctl.d/99-tailscale.conf >/dev/null 2>&1

if [[ -n "$TAILSCALE_AUTHKEY" ]]; then
  tailscale up --authkey="$TAILSCALE_AUTHKEY" --accept-routes >/dev/null 2>&1
  log "Tailscale connected (auth key used)"
else
  warn "Run  'tailscale up'  after install to connect to your tailnet"
fi

section "STEP 4 — Firewall (UFW)"
ufw --force reset >/dev/null 2>&1
ufw default deny incoming >/dev/null 2>&1
ufw default allow outgoing >/dev/null 2>&1
# Allow SSH only from Tailscale subnet (100.64.0.0/10)
ufw allow in on tailscale0 to any port 22 proto tcp >/dev/null 2>&1
# Allow OpenClaw UI only from Tailscale
ufw allow in on tailscale0 to any port "$OPENCLAW_PORT" proto tcp >/dev/null 2>&1
ufw --force enable >/dev/null 2>&1
log "UFW configured — all traffic blocked except Tailscale"

section "STEP 5 — OpenClaw"
mkdir -p "$OPENCLAW_DIR"

# Clone or pull latest
if [[ -d "$OPENCLAW_DIR/.git" ]]; then
  git -C "$OPENCLAW_DIR" pull --quiet
  log "OpenClaw updated"
else
  # Replace with actual OpenClaw repo URL when available
  OPENCLAW_REPO="${OPENCLAW_REPO:-https://github.com/openclaw-ai/openclaw.git}"
  if git clone --quiet "$OPENCLAW_REPO" "$OPENCLAW_DIR" 2>/dev/null; then
    log "OpenClaw cloned from $OPENCLAW_REPO"
  else
    warn "Could not clone OpenClaw repo. Creating placeholder structure..."
    mkdir -p "$OPENCLAW_DIR"/{src,config,logs}
    cat > "$OPENCLAW_DIR/package.json" <<'PKGJSON'
{
  "name": "openclaw",
  "version": "1.0.0",
  "description": "OpenClaw AI Agent",
  "main": "src/index.js",
  "scripts": { "start": "node src/index.js" }
}
PKGJSON
    cat > "$OPENCLAW_DIR/src/index.js" <<'INDEXJS'
const http = require('http');
const PORT = process.env.PORT || 3000;
http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.end('OpenClaw is running!\n');
}).listen(PORT, () => console.log(`OpenClaw listening on :${PORT}`));
INDEXJS
  fi
fi

cd "$OPENCLAW_DIR"
npm install --silent
log "Dependencies installed"

section "STEP 6 — Environment Config"
ENV_FILE="$OPENCLAW_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<EOF
# OpenClaw Environment Configuration
# Generated by one-click installer $(date)

PORT=${OPENCLAW_PORT}

# ── AI Provider (choose one) ──────────────────────────────
# Anthropic Claude (incurs API cost)
# ANTHROPIC_API_KEY=sk-ant-...

# OpenAI
# OPENAI_API_KEY=sk-...

# Local Ollama (free, runs on same VM)
# OLLAMA_BASE_URL=http://localhost:11434

# ── Optional ──────────────────────────────────────────────
# LOG_LEVEL=info
# NODE_ENV=production
EOF
  log ".env file created at $ENV_FILE — add your API key"
else
  log ".env already exists, skipping"
fi
chmod 600 "$ENV_FILE"

section "STEP 7 — Systemd Service (Auto-start)"
cat > /etc/systemd/system/openclaw.service <<EOF
[Unit]
Description=OpenClaw AI Agent
After=network.target tailscaled.service
Wants=tailscaled.service

[Service]
Type=simple
User=ubuntu
WorkingDirectory=${OPENCLAW_DIR}
EnvironmentFile=${OPENCLAW_DIR}/.env
ExecStart=/usr/bin/node src/index.js
Restart=always
RestartSec=10
StandardOutput=append:${OPENCLAW_DIR}/logs/openclaw.log
StandardError=append:${OPENCLAW_DIR}/logs/stderr.log

[Install]
WantedBy=multi-user.target
EOF

mkdir -p "$OPENCLAW_DIR/logs"
chown -R ubuntu:ubuntu "$OPENCLAW_DIR" 2>/dev/null || true
systemctl daemon-reload
systemctl enable openclaw >/dev/null 2>&1
systemctl start openclaw
log "OpenClaw service enabled and started"

# ─── Summary ───────────────────────────────────────────────
TAILSCALE_IP=$(tailscale ip -4 2>/dev/null || echo "<connect tailscale first>")

echo -e "\n${GREEN}${BOLD}╔══════════════════════════════════════════╗"
echo -e "║    OpenClaw Installation Complete! ✅   ║"
echo -e "╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Access URL  :${NC} http://${TAILSCALE_IP}:${OPENCLAW_PORT}"
echo -e "  ${BOLD}Config File :${NC} ${OPENCLAW_DIR}/.env"
echo -e "  ${BOLD}Logs        :${NC} ${OPENCLAW_DIR}/logs/openclaw.log"
echo ""
echo -e "  ${YELLOW}Next Steps:${NC}"
echo -e "  1. Edit ${BOLD}${ENV_FILE}${NC} and add your API key"
echo -e "  2. Run ${BOLD}tailscale up${NC} to connect securely"
echo -e "  3. sudo systemctl restart openclaw"
echo ""
echo -e "  ${CYAN}Useful commands:${NC}"
echo -e "  sudo systemctl status openclaw"
echo -e "  sudo journalctl -u openclaw -f"
echo ""
